apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: translator-app
  template:
    metadata:
      labels:
        app: translator-app
    spec:
      containers:
      - name: translator-app
        image: 614768946157.dkr.ecr.us-east-1.amazonaws.com/translator-app:v2
        ports:
        - containerPort: 5000