apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-2
  version: "1.28"

nodeGroups:
  - name: linux-nodes
    instanceType: t2.micro
    desiredCapacity: 2


