name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the workflow

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_TAG: latest # Or any other tag you prefer

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: translator-app
      run: |
        docker build -t $IMAGE_NAME ./app_code
        docker tag ${{ secrets.TAGGING }}
        docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_NAME
